-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- INF2014.6G

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Fahrradverleih
-- -----------------------------------------------------
-- create user Admin -> Datenbank Administrator
CREATE USER 'Admin' IDENTIFIED BY 'gibbiX12345$';

-- give rights
GRANT ALL ON `Fahrradverleih`.* TO 'Admin';
GRANT ALL ON TABLE `Fahrradverleih`.`Person` TO 'Admin';
GRANT ALL ON TABLE `Fahrradverleih`.`Mitarbeiter` TO 'Admin';
GRANT ALL ON TABLE `Fahrradverleih`.`Adresse` TO 'Admin';
GRANT ALL ON TABLE `Fahrradverleih`.`Kunde` TO 'Admin';
GRANT ALL ON TABLE `Fahrradverleih`.`Verleih` TO 'Admin';
GRANT ALL ON TABLE `Fahrradverleih`.`Velo` TO 'Admin';
GRANT ALL ON TABLE `Fahrradverleih`.`Modell` TO 'Admin';
GRANT ALL ON TABLE `Fahrradverleih`.`Zustand` TO 'Admin';
GRANT ALL ON TABLE `Fahrradverleih`.`Typ` TO 'Admin';
GRANT ALL `Fahrradverleih`.`Marke` TO 'Admin';

-- create user Peter von Egg -> Chef
CREATE USER 'Peter von Egg' IDENTIFIED BY 'gibbiX12345$';

-- give rights
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `Fahrradverleih`.* TO 'Peter von Egg';

GRANT ALL ON TABLE `Fahrradverleih`.`Person` TO 'Peter von Egg';
GRANT ALL ON TABLE `Fahrradverleih`.`Mitarbeiter` TO 'Peter von Egg';
GRANT ALL ON TABLE `Fahrradverleih`.`Adresse` TO 'Peter von Egg';
GRANT ALL ON TABLE `Fahrradverleih`.`Kunde` TO 'Peter von Egg';
GRANT ALL ON TABLE `Fahrradverleih`.`Verleih` TO 'Peter von Egg';
GRANT ALL ON TABLE `Fahrradverleih`.`Velo` TO 'Peter von Egg';
GRANT ALL ON TABLE `Fahrradverleih`.`Modell` TO 'Peter von Egg';
GRANT ALL ON TABLE `Fahrradverleih`.`Zustand` TO 'Peter von Egg';
GRANT ALL ON TABLE `Fahrradverleih`.`Typ` TO 'Peter von Egg';
GRANT ALL ON TABLE `Fahrradverleih`.`Marke` TO 'Peter von Egg';

-- create user Petra von Egg -> Sekretariat
CREATE USER 'Petra von Egg' IDENTIFIED BY 'gibbiX12345$';

-- give rights
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `Fahrradverleih`.* TO 'Petra von Egg';

GRANT ALL ON TABLE `Fahrradverleih`.`Person` TO 'Petra von Egg';
GRANT ALL ON TABLE `Fahrradverleih`.`Mitarbeiter` TO 'Petra von Egg';
GRANT ALL ON TABLE `Fahrradverleih`.`Adresse` TO 'Petra von Egg';
GRANT ALL ON TABLE `Fahrradverleih`.`Kunde` TO 'Petra von Egg';
GRANT ALL ON TABLE `Fahrradverleih`.`Verleih` TO 'Petra von Egg';
GRANT ALL ON TABLE `Fahrradverleih`.`Velo` TO 'Petra von Egg';
GRANT ALL ON TABLE `Fahrradverleih`.`Modell` TO 'Petra von Egg';
GRANT ALL ON TABLE `Fahrradverleih`.`Zustand` TO 'Petra von Egg';
GRANT ALL ON TABLE `Fahrradverleih`.`Typ` TO 'Petra von Egg';
GRANT ALL ON TABLE `Fahrradverleih`.`Marke` TO 'Petra von Egg';
GRANT SELECT, INSERT, TRIGGER ON TABLE `Fahrradverleih`.* TO 'Petra von Egg';
GRANT INSERT, SELECT ON TABLE `Fahrradverleih`.`Person` TO 'Petra von Egg';
GRANT INSERT, SELECT ON TABLE `Fahrradverleih`.`Mitarbeiter` TO 'Petra von Egg';
GRANT INSERT, SELECT ON TABLE `Fahrradverleih`.`Adresse` TO 'Petra von Egg';
GRANT INSERT, SELECT ON TABLE `Fahrradverleih`.`Kunde` TO 'Petra von Egg';
GRANT INSERT, SELECT ON TABLE `Fahrradverleih`.`Verleih` TO 'Petra von Egg';
GRANT INSERT, SELECT ON TABLE `Fahrradverleih`.`Velo` TO 'Petra von Egg';
GRANT INSERT, SELECT ON TABLE `Fahrradverleih`.`Modell` TO 'Petra von Egg';
GRANT INSERT, SELECT ON TABLE `Fahrradverleih`.`Zustand` TO 'Petra von Egg';
GRANT INSERT, SELECT ON TABLE `Fahrradverleih`.`Typ` TO 'Petra von Egg';
GRANT INSERT, SELECT ON TABLE `Fahrradverleih`.`Marke` TO 'Petra von Egg';

-- create user Max Miche -> Mitarbeiter
CREATE USER 'Max Miche' IDENTIFIED BY 'gibbiX12345$';

-- give rights
GRANT SELECT ON TABLE `Fahrradverleih`.* TO 'Max Miche';
GRANT SELECT ON TABLE `Fahrradverleih`.`Person` TO 'Max Miche';
GRANT SELECT ON TABLE `Fahrradverleih`.`Mitarbeiter` TO 'Max Miche';
GRANT SELECT ON TABLE `Fahrradverleih`.`Adresse` TO 'Max Miche';
GRANT SELECT ON TABLE `Fahrradverleih`.`Kunde` TO 'Max Miche';
GRANT SELECT ON TABLE `Fahrradverleih`.`Verleih` TO 'Max Miche';
GRANT SELECT ON TABLE `Fahrradverleih`.`Velo` TO 'Max Miche';
GRANT SELECT ON TABLE `Fahrradverleih`.`Modell` TO 'Max Miche';
GRANT SELECT ON TABLE `Fahrradverleih`.`Zustand` TO 'Max Miche';
GRANT SELECT ON TABLE `Fahrradverleih`.`Typ` TO 'Max Miche';
GRANT SELECT ON TABLE `Fahrradverleih`.`Marke` TO 'Max Miche';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;